/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.GenericDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Agencia;
import model.Cliente;
import model.Contato;
import model.Corrente;
import model.Endereco;
import model.Poupanca;

/**
 *
 * @author Xatuba Pox
 */
public class OpenAccountBankGUI extends javax.swing.JFrame {
    Cliente cliente;
    Endereco endereco;
    Contato contato;
    Corrente corrente;
    Poupanca poupanca;
    Agencia agencia;
    private final GenericDAO<Agencia> agenciaDao;
    /**
     * Creates new form OpenAccountBankGUI
     * @param cliente
     * @param endereco
     * @param contato
     */
    public OpenAccountBankGUI(Cliente cliente,Endereco endereco,Contato contato) {
        initComponents();
        typeComboBox.setSelectedIndex(-1);
        this.cliente = cliente;
        this.endereco = endereco;
        this.contato = contato;
        agenciaDao = new GenericDAO<>();
    }

    private OpenAccountBankGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        openAccountPanel = new javax.swing.JPanel();
        typeComboBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        gainMonthLabel = new javax.swing.JLabel();
        gainMonthField = new javax.swing.JFormattedTextField();
        separatorGainMonth = new javax.swing.JSeparator();
        registerCardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlePanel.setBackground(new java.awt.Color(74, 31, 61));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(187, 187, 187));
        titleLabel.setText("Abrir Conta Bancaria");
        titlePanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(250, 250, 250));
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        titlePanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        openAccountPanel.setBackground(new java.awt.Color(186, 79, 74));
        openAccountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeComboBox.setBackground(new java.awt.Color(186, 79, 74));
        typeComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CORRENTE", "POUPANCA" }));
        openAccountPanel.add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 30));

        typeLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        typeLabel.setText("Tipo de conta:");
        openAccountPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        gainMonthLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gainMonthLabel.setText("Ganho Mensal:");
        openAccountPanel.add(gainMonthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        gainMonthField.setBackground(new java.awt.Color(186, 79, 74));
        gainMonthField.setBorder(null);
        gainMonthField.setForeground(new java.awt.Color(187, 187, 187));
        gainMonthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        gainMonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainMonthFieldActionPerformed(evt);
            }
        });
        openAccountPanel.add(gainMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, 30));

        separatorGainMonth.setBackground(new java.awt.Color(204, 204, 204));
        separatorGainMonth.setForeground(new java.awt.Color(204, 204, 204));
        openAccountPanel.add(separatorGainMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 10));

        registerCardButton.setBackground(new java.awt.Color(186, 79, 74));
        registerCardButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registerCardButton.setForeground(new java.awt.Color(187, 187, 187));
        registerCardButton.setText("Cadastrar Cartao");
        registerCardButton.setBorder(null);
        registerCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerCardButtonMouseClicked(evt);
            }
        });
        registerCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCardButtonActionPerformed(evt);
            }
        });
        openAccountPanel.add(registerCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addComponent(openAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(openAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void registerCardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCardButtonMouseClicked
        agencia = new Agencia("003", 174, endereco);//COLOCAR CAMPOS PARA O ENDERECO E DADOS DA AGENCIA NA TELA
        boolean resposta = agenciaDao.saveOrUpdate(agencia);
        long miliseconds = System.currentTimeMillis();
        Date date = new Date(miliseconds);
        cliente.setNascimento(date);
        if(resposta){
           JOptionPane.showMessageDialog(null, "Agencia Cadastrada"); 
        }
        if(typeComboBox.getSelectedItem().toString().equalsIgnoreCase("corrente")){
            corrente = new Corrente();
            corrente.setAgenciaId(agencia);
            corrente.setGanhoMensal(12.89f);//NAO CONSEGUI FAZER A INSERCAO COM OS DADOS DA TELA
                                            //POIS DEU ERRO DE FORMATACAO
            corrente.setNumero(corrente.gerarNumerodaConta());
            corrente.setDataCriacao(date);
            corrente.setSaldo(0.00f);
            corrente.setStatus(true);
        }else{
            poupanca = new Poupanca();
            poupanca.setAgenciaId(agencia);
            poupanca.setGanhoMensal(Float.valueOf(gainMonthField.getText()));
            poupanca.setGanhoMensal(12.89f);
            poupanca.setNumero(poupanca.gerarNumerodaConta());
            poupanca.setDataCriacao(date);
            poupanca.setSaldo(0.00f);
            poupanca.setStatus(true);
        }
        RegisterCardGUI rc = new RegisterCardGUI(cliente, corrente, poupanca, endereco, contato);
        rc.setVisible(true);
        rc.pack();
        rc.setLocationRelativeTo(null);
        rc.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_registerCardButtonMouseClicked

    private void registerCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCardButtonActionPerformed
        if(typeComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Tipo de conta inválida!");
        } else if(gainMonthField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ganho mensal inválido!");
        }
        
    }//GEN-LAST:event_registerCardButtonActionPerformed

    private void gainMonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainMonthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gainMonthFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenAccountBankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenAccountBankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenAccountBankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenAccountBankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenAccountBankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JFormattedTextField gainMonthField;
    private javax.swing.JLabel gainMonthLabel;
    private javax.swing.JPanel openAccountPanel;
    private javax.swing.JButton registerCardButton;
    private javax.swing.JSeparator separatorGainMonth;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

}
