package view;

import dao.GenericDAO;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Contato;
import model.Endereco;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Xatuba Pox
 */
public class RegisterGUI extends javax.swing.JFrame {

    Cliente cliente;
    Endereco endereco;
    Contato contato;
    
    public RegisterGUI() {
        initComponents();
        estadosComboBox.setSelectedIndex(-1);
        operadoraComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        separatorPass = new javax.swing.JSeparator();
        separatorUser = new javax.swing.JSeparator();
        openAccountBankButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        separatorName = new javax.swing.JSeparator();
        cpfLabel = new javax.swing.JLabel();
        separatorCpf = new javax.swing.JSeparator();
        cpfField = new javax.swing.JFormattedTextField();
        rgLabel = new javax.swing.JLabel();
        rgField = new javax.swing.JTextField();
        separatorRg = new javax.swing.JSeparator();
        ufLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JTextField();
        separatorCep = new javax.swing.JSeparator();
        estadosComboBox = new javax.swing.JComboBox<>();
        cepLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        separatorCity = new javax.swing.JSeparator();
        adressLabel = new javax.swing.JLabel();
        adressField = new javax.swing.JTextField();
        separatorAdress = new javax.swing.JSeparator();
        telLabel = new javax.swing.JLabel();
        telField = new javax.swing.JFormattedTextField();
        separatorTel = new javax.swing.JSeparator();
        operadoraLabel = new javax.swing.JLabel();
        operadoraComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlePanel.setBackground(new java.awt.Color(74, 31, 61));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(187, 187, 187));
        titleLabel.setText("Cadastro de Clientes");
        titlePanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(250, 250, 250));
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        titlePanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        registerPanel.setBackground(new java.awt.Color(186, 79, 74));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailField.setBackground(new java.awt.Color(186, 79, 74));
        emailField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(187, 187, 187));
        emailField.setBorder(null);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        registerPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 30));

        passwordField.setBackground(new java.awt.Color(186, 79, 74));
        passwordField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(187, 187, 187));
        passwordField.setBorder(null);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        registerPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 30));

        separatorPass.setBackground(new java.awt.Color(204, 204, 204));
        separatorPass.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 10));

        separatorUser.setBackground(new java.awt.Color(204, 204, 204));
        separatorUser.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 10));

        openAccountBankButton.setBackground(new java.awt.Color(186, 79, 74));
        openAccountBankButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        openAccountBankButton.setForeground(new java.awt.Color(187, 187, 187));
        openAccountBankButton.setText("Abrir Conta");
        openAccountBankButton.setBorder(null);
        openAccountBankButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openAccountBankButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openAccountBankButtonMouseClicked(evt);
            }
        });
        openAccountBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAccountBankButtonActionPerformed(evt);
            }
        });
        registerPanel.add(openAccountBankButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 90, 30));

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passwordLabel.setText("Senha da conta:");
        registerPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 50));

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        emailLabel.setText("Email:");
        registerPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameLabel.setText("Nome:");
        registerPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        nameField.setBackground(new java.awt.Color(186, 79, 74));
        nameField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameField.setForeground(new java.awt.Color(187, 187, 187));
        nameField.setBorder(null);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        registerPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, 30));

        separatorName.setBackground(new java.awt.Color(204, 204, 204));
        separatorName.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, 10));

        cpfLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cpfLabel.setText("CPF:");
        registerPanel.add(cpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        separatorCpf.setBackground(new java.awt.Color(204, 204, 204));
        separatorCpf.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 200, 10));

        cpfField.setBackground(new java.awt.Color(186, 79, 74));
        cpfField.setBorder(null);
        cpfField.setForeground(new java.awt.Color(187, 187, 187));
        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        registerPanel.add(cpfField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, 30));

        rgLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rgLabel.setText("RG:");
        registerPanel.add(rgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        rgField.setBackground(new java.awt.Color(186, 79, 74));
        rgField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rgField.setForeground(new java.awt.Color(187, 187, 187));
        rgField.setBorder(null);
        rgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgFieldActionPerformed(evt);
            }
        });
        registerPanel.add(rgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, 30));

        separatorRg.setBackground(new java.awt.Color(204, 204, 204));
        separatorRg.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 200, 10));

        ufLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ufLabel.setText("UF:");
        registerPanel.add(ufLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        cepField.setBackground(new java.awt.Color(186, 79, 74));
        cepField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cepField.setForeground(new java.awt.Color(187, 187, 187));
        cepField.setBorder(null);
        cepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepFieldActionPerformed(evt);
            }
        });
        registerPanel.add(cepField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 200, 30));

        separatorCep.setBackground(new java.awt.Color(204, 204, 204));
        separatorCep.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, 10));

        estadosComboBox.setBackground(new java.awt.Color(186, 79, 74));
        estadosComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        estadosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadosComboBoxActionPerformed(evt);
            }
        });
        registerPanel.add(estadosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, 30));

        cepLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cepLabel.setText("CEP:");
        registerPanel.add(cepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        cityLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cityLabel.setText("Cidade:");
        registerPanel.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        cityField.setBackground(new java.awt.Color(186, 79, 74));
        cityField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cityField.setForeground(new java.awt.Color(187, 187, 187));
        cityField.setBorder(null);
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        registerPanel.add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 200, 30));

        separatorCity.setBackground(new java.awt.Color(204, 204, 204));
        separatorCity.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 200, 10));

        adressLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        adressLabel.setText("Endereco:");
        registerPanel.add(adressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        adressField.setBackground(new java.awt.Color(186, 79, 74));
        adressField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        adressField.setForeground(new java.awt.Color(187, 187, 187));
        adressField.setBorder(null);
        adressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldActionPerformed(evt);
            }
        });
        registerPanel.add(adressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 200, 30));

        separatorAdress.setBackground(new java.awt.Color(204, 204, 204));
        separatorAdress.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 200, 10));

        telLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        telLabel.setText("Telefone:");
        registerPanel.add(telLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        telField.setBackground(new java.awt.Color(186, 79, 74));
        telField.setBorder(null);
        telField.setForeground(new java.awt.Color(187, 187, 187));
        try {
            telField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        registerPanel.add(telField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 200, 30));

        separatorTel.setBackground(new java.awt.Color(204, 204, 204));
        separatorTel.setForeground(new java.awt.Color(204, 204, 204));
        registerPanel.add(separatorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 200, 10));

        operadoraLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        operadoraLabel.setText("Operadora:");
        registerPanel.add(operadoraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        operadoraComboBox.setBackground(new java.awt.Color(186, 79, 74));
        operadoraComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        operadoraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vivo", "Claro", "Oi", "Tim", "Nextel" }));
        operadoraComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadoraComboBoxActionPerformed(evt);
            }
        });
        registerPanel.add(operadoraComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 200, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void openAccountBankButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAccountBankButtonMouseClicked
        try{
           cliente = new Cliente();
            cliente.setEmailLogin(emailField.getText());
            cliente.setSenhaLogin(passwordField.getText());
            cliente.setNome(nameField.getText());
            cliente.setCpf(cpfField.getText());
            cliente.setRg(rgField.getText());
            endereco = new Endereco();
            endereco.setCep(cepField.getText());
            endereco.setEstado(estadosComboBox.getActionCommand());//ainda não descobri como pegar dados de comboBox
            endereco.setCidade(cityField.getText());
            endereco.setEndereco(adressField.getText());
            contato = new Contato();
            contato.setNumero(telField.getText());
            contato.setOperadora(operadoraComboBox.getActionCommand());
            OpenAccountBankGUI oab = new OpenAccountBankGUI(cliente, endereco, contato); 
            oab.setVisible(true);
            oab.pack();
            oab.setLocationRelativeTo(null);
            oab.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro na inserção dos dados");
        }
    }//GEN-LAST:event_openAccountBankButtonMouseClicked

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void rgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgFieldActionPerformed

    private void cepFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void adressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressFieldActionPerformed

    private void estadosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadosComboBoxActionPerformed

    private void operadoraComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operadoraComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operadoraComboBoxActionPerformed

    private void openAccountBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAccountBankButtonActionPerformed
        if(emailField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Email inválido!");
        } else if(passwordField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Senha inválida!");
        } else if(nameField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nome inválido!");
        } else if(cpfField.getText().trim().length() < 14) {
            JOptionPane.showMessageDialog(null, "CPF inválido!");
        } else if(rgField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "RG inválido!");
        } else if(cepField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CEP inválido!");
        } else if(estadosComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Estado inválido!");
        } else if(cityField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cidade inválida!");
        } else if(adressField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Endereço inválido!");
        } else if(telField.getText().trim().length() < 13) {
            JOptionPane.showMessageDialog(null, "Telefone inválido!");
        } else if(operadoraComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Operadora inválida!");
        }
    }//GEN-LAST:event_openAccountBankButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressField;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> estadosComboBox;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton openAccountBankButton;
    private javax.swing.JComboBox<String> operadoraComboBox;
    private javax.swing.JLabel operadoraLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField rgField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JSeparator separatorAdress;
    private javax.swing.JSeparator separatorCep;
    private javax.swing.JSeparator separatorCity;
    private javax.swing.JSeparator separatorCpf;
    private javax.swing.JSeparator separatorName;
    private javax.swing.JSeparator separatorPass;
    private javax.swing.JSeparator separatorRg;
    private javax.swing.JSeparator separatorTel;
    private javax.swing.JSeparator separatorUser;
    private javax.swing.JFormattedTextField telField;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel ufLabel;
    // End of variables declaration//GEN-END:variables
}
