/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.GenericDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Cartao;
import model.Cliente;
import model.Contato;
import model.Corrente;
import model.Endereco;
import model.Poupanca;

/**
 *
 * @author Xatuba Pox
 */
public class RegisterCardGUI extends javax.swing.JFrame {

    Cliente cliente;
    Endereco endereco;
    Contato contato;
    Corrente corrente;
    Poupanca poupanca;
    Cartao cartao;
    private final GenericDAO<Corrente> correnteDao;
    private final GenericDAO<Poupanca> poupancaDao;
    private final GenericDAO<Cliente> clienteDao;
    private final GenericDAO<Cartao> cartaoDao;
    private final GenericDAO<Endereco> enderecoDao;
    private final GenericDAO<Contato> contatoDao;
    /**
     * Creates new form RegisterCardGUI
     * @param cliente
     * @param corrente
     * @param poupanca
     * @param endereco
     * @param contato
     */
    public RegisterCardGUI(Cliente cliente, Corrente corrente, Poupanca poupanca, Endereco endereco, Contato contato) {
        initComponents();
        typeCartaoCb.setSelectedIndex(-1);
        this.cliente = cliente;
        this.contato = contato;
        this.endereco = endereco;
        this.corrente = corrente;
        this.poupanca = poupanca;
        correnteDao = new GenericDAO<>();
        poupancaDao = new GenericDAO<>();
        clienteDao = new GenericDAO<>();
        cartaoDao = new GenericDAO<>();
        enderecoDao = new GenericDAO<>();
        contatoDao = new GenericDAO<>();
    }

    public RegisterCardGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        registerCardPanel = new javax.swing.JPanel();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        separatorPass = new javax.swing.JSeparator();
        registerCardButton = new javax.swing.JButton();
        passLabel1 = new javax.swing.JLabel();
        typeCartaoCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlePanel.setBackground(new java.awt.Color(74, 31, 61));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(187, 187, 187));
        titleLabel.setText("Registrar Cartao");
        titlePanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(250, 250, 250));
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        titlePanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        registerCardPanel.setBackground(new java.awt.Color(186, 79, 74));
        registerCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passLabel.setText("Tipo de cartão:");
        registerCardPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        passField.setBackground(new java.awt.Color(186, 79, 74));
        passField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passField.setForeground(new java.awt.Color(187, 187, 187));
        passField.setBorder(null);
        registerCardPanel.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 30));

        separatorPass.setBackground(new java.awt.Color(204, 204, 204));
        separatorPass.setForeground(new java.awt.Color(204, 204, 204));
        registerCardPanel.add(separatorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 200, 10));

        registerCardButton.setBackground(new java.awt.Color(186, 79, 74));
        registerCardButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registerCardButton.setForeground(new java.awt.Color(187, 187, 187));
        registerCardButton.setText("Registrar Cliente");
        registerCardButton.setBorder(null);
        registerCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerCardButtonMouseClicked(evt);
            }
        });
        registerCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCardButtonActionPerformed(evt);
            }
        });
        registerCardPanel.add(registerCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 30));

        passLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passLabel1.setText("Senha do cartão:");
        registerCardPanel.add(passLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        typeCartaoCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito", "Os dois" }));
        registerCardPanel.add(typeCartaoCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addComponent(registerCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(registerCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void registerCardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCardButtonMouseClicked
        cartao = new Cartao();
        if(typeCartaoCb.getSelectedItem().toString().equalsIgnoreCase("crédito")){
            cartao.setCredito(true);
            cartao.setDebito(false);
            cartao.setCvc((short) cartao.gerarCvc());
            cartao.setNumero(cartao.gerarNumeroFormatado());
            if(poupanca == null)
                cartao.setLimiteTotal(corrente.getGanhoMensal());
            else
                cartao.setLimiteTotal(poupanca.getGanhoMensal());
            cartao.setLimiteUsado(0.00f);
            cartao.setTitular(cliente.getNome());
            cartao.setSenha(passField.getText());
            cartao.setSituacao(true);
            long miliseconds = System.currentTimeMillis();
            Date date = new Date(miliseconds);
            cartao.setValidade(Cartao.somaData(date));
        }else if(typeCartaoCb.getSelectedItem().toString().equalsIgnoreCase("débito")){
            cartao.setCredito(false);
            cartao.setDebito(true);
            cartao.setCvc((short) cartao.gerarCvc());
            cartao.setNumero(cartao.gerarNumeroFormatado());
            cartao.setLimiteTotal(0.00f);
            cartao.setLimiteUsado(0.00f);
            cartao.setTitular(cliente.getNome());
            cartao.setSenha(passField.getText());
            cartao.setSituacao(true);
            long miliseconds = System.currentTimeMillis();
            Date date = new Date(miliseconds);
            cartao.setValidade(Cartao.somaData(date));
        }else{
            cartao.setCredito(true);
            cartao.setDebito(true);
            cartao.setCvc((short) cartao.gerarCvc());
            cartao.setNumero(cartao.gerarNumeroFormatado());
            if(poupanca == null)
                cartao.setLimiteTotal(corrente.getGanhoMensal());
            else
                cartao.setLimiteTotal(poupanca.getGanhoMensal());
            cartao.setLimiteUsado(0.00f);
            cartao.setTitular(cliente.getNome());
            cartao.setSenha(passField.getText());
            cartao.setSituacao(true);
            long miliseconds = System.currentTimeMillis();
            Date date = new Date(miliseconds);
            cartao.setValidade(Cartao.somaData(date));
        }
        boolean resposta  = cartaoDao.saveOrUpdate(cartao);
        if(resposta){
            JOptionPane.showMessageDialog(null, "Cartão cadastrado"); 
            if(poupanca == null){
                corrente.setCartaoId(cartao);
                resposta = correnteDao.saveOrUpdate(corrente);
            }else{
                poupanca.setCartaoId(cartao);
                resposta = poupancaDao.saveOrUpdate(poupanca);
            }
            if(resposta){
                JOptionPane.showMessageDialog(null, "Conta cadastrada");
                cliente.setCorrenteId(corrente);
                cliente.setPoupancaId(poupanca);
                cliente.setComprovanteResidencia(false);
                clienteDao.saveOrUpdate(cliente);
                endereco.setClienteId(cliente);
                contato.setClienteId(cliente);
                enderecoDao.saveOrUpdate(endereco);
                contatoDao.saveOrUpdate(contato);
            }
        }
        
        LoginGUI log = new LoginGUI();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_registerCardButtonMouseClicked

    private void registerCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCardButtonActionPerformed
        if(passField.getPassword().length > 6 || passField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Senha inválida... Aceita até 6 caracteres!");
        } else if (typeCartaoCb.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Tipo de cartão inválido!");
        }
    }//GEN-LAST:event_registerCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JButton registerCardButton;
    private javax.swing.JPanel registerCardPanel;
    private javax.swing.JSeparator separatorPass;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JComboBox<String> typeCartaoCb;
    // End of variables declaration//GEN-END:variables
}
