/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Cliente;


/**
 *
 * @author João
 */
public class ShowAccountDataGUI extends javax.swing.JFrame {
    Cliente cliente;
    /**
     * Creates new form ShowAccountDataGUI
     * @param cliente
     */
    public ShowAccountDataGUI(Cliente cliente) {
        initComponents();
        txNumeroBanco.setEditable(false);
        txNumeroConta.setEditable(false);
        txData.setEditable(false);
        txGnaho.setEditable(false);
        this.cliente = cliente;
        if(cliente.getPoupancaId() != null){
            txNumeroBanco.setText(Integer.toString(cliente.getPoupancaId().getAgenciaId().getNumeroBanco()));
            txNumeroConta.setText(cliente.getPoupancaId().getNumero());
            Date data = cliente.getPoupancaId().getDataCriacao();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String dataFormatada = dateFormat.format(data);
            txData.setText(dataFormatada);
            txGnaho.setText("R$" + String.valueOf(cliente.getPoupancaId().getGanhoMensal()));
        }else{
            txNumeroBanco.setText(Integer.toString(cliente.getCorrenteId().getAgenciaId().getNumeroBanco()));
            txNumeroConta.setText(cliente.getCorrenteId().getNumero());
            Date data = cliente.getCorrenteId().getDataCriacao();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String dataFormatada = dateFormat.format(data);
            txData.setText(dataFormatada);
            txGnaho.setText("R$" + String.valueOf(cliente.getCorrenteId().getGanhoMensal()));
        }
    }
    
    public ShowAccountDataGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        ufLabel = new javax.swing.JLabel();
        cepLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        telLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txGnaho = new javax.swing.JTextField();
        txNumeroBanco = new javax.swing.JTextField();
        txNumeroConta = new javax.swing.JTextField();
        txData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlePanel.setBackground(new java.awt.Color(74, 31, 61));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(250, 250, 250));
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        titlePanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        titleLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(187, 187, 187));
        titleLabel1.setText("Dados da Conta");
        titlePanel.add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        registerPanel.setBackground(new java.awt.Color(186, 79, 74));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ufLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ufLabel.setText("Numero da Conta:");
        registerPanel.add(ufLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cepLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cepLabel.setText("Numero do Banco:");
        registerPanel.add(cepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        cityLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cityLabel.setText("Data de Criação:");
        registerPanel.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        next.setBackground(new java.awt.Color(186, 79, 74));
        next.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        next.setForeground(new java.awt.Color(187, 187, 187));
        next.setText("Detalhamento");
        next.setBorder(null);
        next.setBorderPainted(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        registerPanel.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 40));

        Previous.setBackground(new java.awt.Color(186, 79, 74));
        Previous.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Previous.setForeground(new java.awt.Color(187, 187, 187));
        Previous.setText("Perfil");
        Previous.setBorder(null);
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });
        registerPanel.add(Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 80, 30));

        Logout.setBackground(new java.awt.Color(186, 79, 74));
        Logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(187, 187, 187));
        Logout.setText("Logout");
        Logout.setBorder(null);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        registerPanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 80, 30));

        telLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        telLabel1.setText("Ganho Mensal:");
        registerPanel.add(telLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel2.setText("Clique em \"Detalhamento\" para saldo detalhado");
        registerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txGnaho.setBackground(new java.awt.Color(186, 79, 74));
        txGnaho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGnahoActionPerformed(evt);
            }
        });
        registerPanel.add(txGnaho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 210, 30));

        txNumeroBanco.setBackground(new java.awt.Color(186, 79, 74));
        txNumeroBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumeroBancoActionPerformed(evt);
            }
        });
        registerPanel.add(txNumeroBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 210, 30));

        txNumeroConta.setBackground(new java.awt.Color(186, 79, 74));
        registerPanel.add(txNumeroConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, 30));

        txData.setBackground(new java.awt.Color(186, 79, 74));
        registerPanel.add(txData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        LoginGUI reg = new LoginGUI();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed

        ShowDataGUI opt = new ShowDataGUI(cliente);
        opt.setVisible(true);
        opt.pack();
        opt.setLocationRelativeTo(null);
        opt.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_PreviousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        ShowDetailsGUI opt = new ShowDetailsGUI(cliente);
        opt.setVisible(true);
        opt.pack();
        opt.setLocationRelativeTo(null);
        opt.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void txGnahoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGnahoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txGnahoActionPerformed

    private void txNumeroBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumeroBancoActionPerformed
    
    }//GEN-LAST:event_txNumeroBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAccountDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAccountDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAccountDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAccountDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAccountDataGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Previous;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel telLabel1;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txData;
    private javax.swing.JTextField txGnaho;
    private javax.swing.JTextField txNumeroBanco;
    private javax.swing.JTextField txNumeroConta;
    private javax.swing.JLabel ufLabel;
    // End of variables declaration//GEN-END:variables
}
